version: '3.8'

services:
  infinite-text-game:
    image: atonasting/infinite-text-game:latest
    container_name: infinite-text-game
    environment:
        - WebProxy=xxx # set proxy, for example: http://ip:port or socks5://ip:port
        - Type=OpenAI # OpenAI or Azure
        - OpenAIApiKey=xxx # (OpenAI only) set api key 
        - DefaultModel=xxx # (OpenAI only) set model name like 'gpt-3.5-turbo-16k-0613' or 'gpt-4-0613' etc.
        - AzureApiKey=xxx # (Azure only) set api key 
        - ResourceName=xxx # (Azure only) resource name for endpoint: https://{ResourceName}.openai.azure.com/
        - DeploymentId=xxx # (Azure only) deployment id in azure openAi studio
    ports:
        - '9000:80'
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/etc/timezone:/etc/timezone:ro"